# fly.toml app configuration file generated for cbassuarez-cli on 2026-05-01T23:44:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cbassuarez-cli'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  GEMINI_ADDR = '0.0.0.0:1965'
  SSH_ADDR = '0.0.0.0:2222'
  GEMINI_CERT_PATH = '/tmp/cli-server-secrets/gemini.crt'
  GEMINI_HOST = 'gemini.cbassuarez.com'
  GEMINI_KEY_PATH = '/tmp/cli-server-secrets/gemini.key'
  LETTER_URL = 'https://cbassuarez.com/.well-known/cli-letter.txt'
  SSH_HOST_KEY_PATHS = '/tmp/cli-server-secrets/ssh_host_ed25519'
  WORKER_URL = 'https://seb-feed.cbassuarez.workers.dev'

[[services]]
  protocol = 'tcp'
  internal_port = 2222

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    interval = '30s'
    timeout = '5s'

[[services]]
  protocol = 'tcp'
  internal_port = 1965

  [[services.ports]]
    port = 1965

  [[services.tcp_checks]]
    interval = '30s'
    timeout = '5s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
